sudo: required
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_660223573b0f_key -iv $encrypted_660223573b0f_iv -in k8s/multik8s-serviceaccount.json.enc -out multik8s-serviceaccount.json -d
  - curl https://sdk.clound.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc 
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  
