sudo: required
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_660223573b0f_key -iv $encrypted_660223573b0f_iv -in k8s/multik8s-serviceaccount.json.enc -out multik8s-serviceaccount.json -d
  - curl https://sdk.clound.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc 
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-263015
  - gcloud config set compute/zone us-central1-a	
  - gcloud container clusters get-creddentials  multi-k8-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
  - docker build -t tkavuri/react-test -f ./client/Dockerfile.dev .


script:
        - docker run -e CI=true tkavuri/react-test npm test 

        - docker build -t tkavuri/react-test -f ./client/Dockerfile.dev ./client
        - docker build -t tkavuri/multi-api ./server
        - docker build -t tkavuri/multi-worker ./worker
        - docker build -t tkavuri/multi-nginx ./nginx


  
