apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
          
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres  
  template: 
    metadata:
      labels:
        component: postgres
    
    spec:
      volumes: 
        - name: postgres-storage
          persistentVolumeClaim: 
            claimName: database-persistent-volume-claim
      containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
            subPath: postgres
        env:
          - name: PGPORT
            value: '5432'
          - name: POSTGRESQL_DATABASE
            value: 'postgres'
          - name: POSTGRESQL_PASSWORD
            value: 'postgres'
            - name: POSTGRES_USER
            value: 'postgres'
          - name: PGPORT
            value: '5432'
          - name: POSTGRES_DB
            value: 'postgres'
          - name: POSTGRES_PASSWORD
            value: 'postgres'
            #valueFrom:
            #   secretKeyRef: 
            #    name: pgpassword
            #    key: PGPASSWORD
          - name: PGPASSWORD
            value: postgres
            #valueFrom:
            #  secretKeyRef: 
            #    name: pgpassword
            #    key: PGPASSWORD
            #    POSTGRESQL_USER POSTGRESQL_PASSWORD POSTGRESQL_DATABASE
