apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      component: api  
  template: 
    metadata:
      labels:
        component: api
    
    spec:
      containers:
      - name: api
        image: tkavuri/multi-api
        ports:
          - containerPort: 5000
        env: 
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: PGHOST
            value: postgres-cluster-ip-service
          - name: PGPORT
            value: '5432'
          - name: PGUSER
            value: redis-cluster-ip-service
          - name: PGPORT
            value: '5432'
          - name: PGDATABSE
            value: postgres          
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef: 
                name: pgpassword
                key: PGPASSWORD